const OBSIDIAN_BASE = '../obsidian'
const OBSIDIAN_CV = '10-cv'
const OBSIDIAN_TRANSLATIONS = 'translations'
const OBSIDIAN_PERSONAL = 'personal'
const OBSIDIAN_JOB = 'job'
const OBSIDIAN_SKILL = 'skills'
const OBSIDIAN_LANGUAGE = 'language'
const OBSIDIAN_EDUCATION = 'education'

const OBSIDIAN_CV_TRANSLATION_MAP = OBSIDIAN_BASE + '/' + OBSIDIAN_CV + '/' + OBSIDIAN_TRANSLATIONS + '/'
export default OBSIDIAN_CV_TRANSLATION_MAP

export const OBSIDIAN_CV_PERSONAL_MAP = OBSIDIAN_BASE + '/' + OBSIDIAN_CV + '/' + OBSIDIAN_PERSONAL + '/'
export const OBSIDIAN_CV_JOB_MAP = OBSIDIAN_BASE + '/' + OBSIDIAN_CV + '/' + OBSIDIAN_JOB + '/'

export const OBSIDIAN_CV_SKILL_MAP = OBSIDIAN_BASE + '/' + OBSIDIAN_CV + '/' + OBSIDIAN_SKILL + '/'
export const OBSIDIAN_CV_LANGUAGE_MAP = OBSIDIAN_BASE + '/' + OBSIDIAN_CV + '/' + OBSIDIAN_LANGUAGE + '/'
export const OBSIDIAN_CV_EDUCATION_MAP = OBSIDIAN_BASE + '/' + OBSIDIAN_CV + '/' + OBSIDIAN_EDUCATION + '/'

