const OBSIDIAN_BASE = '../obsidian'
const OBSIDIAN_CV = '10-cv'
const OBSIDIAN_TRANSLATIONS = 'translations'
const OBSIDIAN_PERSONAL = 'personal'

const OBSIDIAN_CV_TRANSLATION_MAP = OBSIDIAN_BASE + '/' + OBSIDIAN_CV + '/' + OBSIDIAN_TRANSLATIONS + '/'
export default OBSIDIAN_CV_TRANSLATION_MAP

export const OBSIDIAN_CV_PERSONAL_MAP = OBSIDIAN_BASE + '/' + OBSIDIAN_CV + '/' + OBSIDIAN_PERSONAL + '/'
